# Generated by Django 5.0.14 on 2026-02-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldWorldFactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OldWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('forces_of_evil_page', models.IntegerField()),
                ('arcane_journal_page', models.IntegerField()),
                ('points_cost', models.IntegerField()),
                ('is_built', models.BooleanField(default=False)),
                ('is_painted', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='old_world_units', to='wh_old_world.oldworldfactions')),
            ],
        ),
    ]
