# Generated by Django 5.0.14 on 2026-02-25 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(choices=[('Blood Angels', 'Blood Angels'), ('Dark Angels', 'Dark Angels'), ('Salamanders', 'Salamanders'), ('Ultramarines', 'Ultramarines'), ('Chaos Space Marines', 'Chaos Space Marines'), ('Astra Militarum', 'Astra Militarum'), ('Orks', 'Orks'), ('Necrons', 'Necrons'), ('Tau', 'Tau'), ('Tyranids', 'Tyranids'), ('Genestealer Cults', 'Genestealer Cults'), ('Chaos Daemons', 'Chaos Daemons'), ('Sisters of Battle', 'Sisters of Battle'), ('Adeptus Mechanicus', 'Adeptus Mechanicus'), ('Adeptus Custodes', 'Adeptus Custodes'), ('Grey Knights', 'Grey Knights'), ('Death Guard', 'Death Guard'), ('Thousand Sons', 'Thousand Sons'), ('Harlequins', 'Harlequins'), ('Drukhari', 'Drukhari'), ('Craftworlds', 'Craftworlds'), ('Ynnari', 'Ynnari'), ('Imperial Knights', 'Imperial Knights'), ('Chaos Knights', 'Chaos Knights')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='wh40k',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('HQ', 'HQ'), ('Troops', 'Troops'), ('Elites', 'Elites'), ('Fast Attack', 'Fast Attack'), ('Heavy Support', 'Heavy Support'), ('Flyer', 'Flyer'), ('Dedicated Transport', 'Dedicated Transport'), ('Lord of War', 'Lord of War'), ('Fortification', 'Fortification')], default='Troops', max_length=50)),
                ('codex_page', models.IntegerField()),
                ('points_cost', models.IntegerField()),
                ('is_built', models.BooleanField(default=False)),
                ('is_painted', models.BooleanField(default=False)),
                ('faction', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='force_orgs', to='wh_40k.factions')),
            ],
        ),
    ]
