# Generated by Django 5.0.14 on 2026-02-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForceOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('codex_page', models.IntegerField()),
                ('points_cost', models.IntegerField()),
                ('is_built', models.BooleanField(default=False)),
                ('is_painted', models.BooleanField(default=False)),
            ],
        ),
    ]
