# Generated by Django 5.0.14 on 2026-02-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force_org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forceorg',
            name='unit_type',
            field=models.CharField(choices=[('HQ', 'HQ'), ('Troops', 'Troops'), ('Elites', 'Elites'), ('Fast Attack', 'Fast Attack'), ('Heavy Support', 'Heavy Support'), ('Flyer', 'Flyer'), ('Dedicated Transport', 'Dedicated Transport'), ('Lord of War', 'Lord of War'), ('Fortification', 'Fortification')], default='Troops', max_length=50),
        ),
    ]
