# Generated by Django 5.0.14 on 2026-02-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force_org', '0002_alter_forceorg_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction_name', models.CharField(choices=[('Space Marines', 'Space Marines'), ('Chaos Space Marines', 'Chaos Space Marines'), ('Astra Militarum', 'Astra Militarum'), ('Orks', 'Orks'), ('Necrons', 'Necrons'), ('Tau', 'Tau'), ('Tyranids', 'Tyranids'), ('Genestealer Cults', 'Genestealer Cults'), ('Chaos Daemons', 'Chaos Daemons'), ('Sisters of Battle', 'Sisters of Battle'), ('Adeptus Mechanicus', 'Adeptus Mechanicus'), ('Adeptus Custodes', 'Adeptus Custodes'), ('Grey Knights', 'Grey Knights'), ('Death Guard', 'Death Guard'), ('Thousand Sons', 'Thousand Sons'), ('Harlequins', 'Harlequins'), ('Drukhari', 'Drukhari'), ('Craftworlds', 'Craftworlds'), ('Ynnari', 'Ynnari'), ('Imperial Knights', 'Imperial Knights'), ('Chaos Knights', 'Chaos Knights')], max_length=100)),
            ],
        ),
    ]
