# Generated by Django 5.0.14 on 2026-02-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('force_org', '0003_factions'),
    ]

    operations = [
        migrations.AddField(
            model_name='forceorg',
            name='faction',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='force_orgs', to='force_org.factions'),
        ),
        migrations.AlterField(
            model_name='factions',
            name='faction_name',
            field=models.CharField(choices=[('Blood Angels', 'Blood Angels'), ('Dark Angels', 'Dark Angels'), ('Salamanders', 'Salamanders'), ('Ultramarines', 'Ultramarines'), ('Chaos Space Marines', 'Chaos Space Marines'), ('Astra Militarum', 'Astra Militarum'), ('Orks', 'Orks'), ('Necrons', 'Necrons'), ('Tau', 'Tau'), ('Tyranids', 'Tyranids'), ('Genestealer Cults', 'Genestealer Cults'), ('Chaos Daemons', 'Chaos Daemons'), ('Sisters of Battle', 'Sisters of Battle'), ('Adeptus Mechanicus', 'Adeptus Mechanicus'), ('Adeptus Custodes', 'Adeptus Custodes'), ('Grey Knights', 'Grey Knights'), ('Death Guard', 'Death Guard'), ('Thousand Sons', 'Thousand Sons'), ('Harlequins', 'Harlequins'), ('Drukhari', 'Drukhari'), ('Craftworlds', 'Craftworlds'), ('Ynnari', 'Ynnari'), ('Imperial Knights', 'Imperial Knights'), ('Chaos Knights', 'Chaos Knights')], max_length=100, unique=True),
        ),
    ]
